//app/layout.tsx
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
 import { Work_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";

 const workSans = Work_Sans({
  variable: "--font-Work_Sans",
  subsets: ["latin"],
  display: "swap",
  preload: false, // Disable font preloading to avoid fetch issues
  adjustFontFallback: false
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${workSans.variable}`}
      >
        <Theme accentColor="cyan" radius="small">
      
          <NavBar />
          <main className="p-6 flex justify-center">
          <div className="max-w-7xl flex justify-center w-[100%] ">
          {children}
          </div>
      
          </main>
        </Theme>
      </body>
    </html>
  );
}
